import propsJson from "@/lib/generated/props.json";
import usageJson from "@/lib/generated/usage.json";

export interface PropDoc {
  name: string;
  type: string;
  required: boolean;
  default: string | null;
  description: string;
}

export interface ComponentPropDocs {
  interface: string;
  extends: string[];
  props: PropDoc[];
}

/** Generated by scripts/extract-props.mjs — rerun it after adding components. */
export function getPropDocs(slug: string): ComponentPropDocs | undefined {
  return (propsJson as Record<string, ComponentPropDocs>)[slug];
}

/** The gallery preview's JSX, verbatim — doubles as the usage example. */
export function getUsage(slug: string): string | undefined {
  return (usageJson as Record<string, string>)[slug];
}
